### ISSUE TITLE
Grid FFT maximum entropy expansion moves the core grid cells  

### ISSUE THREAD

**Issue by orerocks** [GeosoftInc/gxpy#118]
If you use **maximum entropy** method for FFT padding:
```fft = gxfft.GridFFT(grid, expand=20, trend_order=1, fill_method=0)```
to create a padded FFT and then extract the the expanded grid:
```newgrid = fft.expanded_filled_grid```

The padded points and the original grid points are all shifted by half a cell to the west. This implies that the whole grid is getting resampled when it is padded, rather than just filling the empty grid cells. This does not occur for with the minimum curvature fill method.

Here are the grid points and filled-expanded padding points for **maximum entropy**:
![image](https://user-images.githubusercontent.com/31866231/76258633-361c1e80-6211-11ea-8960-f4131d8f603e.png)

Here are the grid points and filled-expanded padding points for **minimum curvature**:
![image](https://user-images.githubusercontent.com/31866231/76258649-3caa9600-6211-11ea-8005-fffe05310f36.png)

I've tried to make some simple changes to `grid_fft.py` to remove the shift, but have not had luck.

**Comment by orerocks** [comment]
If both the original (`grid`) and padded grids (`newgrid`) are saved out of Python as Geosoft grid files the padded grid also shows the same half cell to the west shift when display on top of each other in a an Oasis Montaj map.

It seems that manually adding half a cell width to the x coordinate fixes the problem.

**Comment by serban-seeq** [comment]
related to BASE-34. 

There is a known discrepancy between different gridding methods.

direct gridding does not center cells on the data point location (of the most bottom left data point). Instead it chooses bottom left location so that it is the closest multiple of the cell size. For example I have a point at 717578.9875 and 4553459.1 and cellsize 50. In this case it will choose the bottom left to be at 717600 and 4553450.

Minimum Curvature which is used for the expanded_filled_grid does indeed center cells on the data point location. 

Closing as this is a logged core issue
